/* The site manager. Vanilla ES modules, no framework, no build step — same as the
   rest of this repo, and for the same reason: a chapter officer's website should
   still be editable in five years without anyone reinstalling a toolchain.

   ⛔ NOTHING HERE IS A SECURITY CONTROL. Every check in this file is a courtesy to
   the person using it. The real validation is functions/api/save.js, which does
   not trust a single byte of what this sends. If the two ever disagree, the
   endpoint is right.

   The preview renders with js/blocks.js — the SAME module the Worker uses at save
   time. That is what the dual-runtime byte-match test buys: what an officer sees
   before saving is generated by the identical code that generates what ships. */
import { renderPage } from '../js/blocks.js';
import { validateContent, contentFingerprint } from '../js/validate-content.js';
import { FIELDS, BLOCK_LABELS, BLOCK_DEFAULTS, linesToText, textToLines, isSimpleLines } from './fields.js';

const $ = (sel, root = document) => root.querySelector(sel);
const el = (tag, props = {}, kids = []) => {
  const node = Object.assign(document.createElement(tag), props);
  for (const kid of [].concat(kids)) node.append(kid);
  return node;
};

const state = { content: null, site: null, sel: null, dirty: false, saving: false, base: null, focusItem: null, note: '' };

/* ---------- loading ---------- */

async function loadSite() {
  /* Cache-busted, because the officer may have saved minutes ago and a stale copy
     would silently discard whatever they just published. */
  /* Straight from the branch (/api/content), so an officer who saved a minute ago and reopens
     the editor doesn't load the pre-save copy the not-yet-rebuilt site still serves. Falls back
     to the deployed files if that endpoint is unavailable. */
  let content, site;
  try {
    const r = await fetch('../api/content', { cache: 'no-store' }).then((x) => x.json());
    if (!r.ok) throw new Error(r.error);
    ({ content, site } = r);
  } catch {
    const bust = '?t=' + Date.now();
    [content, site] = await Promise.all([
      fetch('../content/pages.json' + bust).then((r) => r.json()),
      fetch('../content/site.json' + bust).then((r) => r.json()),
    ]);
  }
  state.content = content;
  state.site = site;
  state.base = await contentFingerprint(content, site);
  state.sel = { page: 0, path: null };
}

/* ---------- selection paths ----------
   A block is addressed by the chain of indexes that reaches it, so the same code
   handles a top-level block and one nested inside a split's left column. */

function containerAt(page, path) {
  // path: { section, chain: [{ index, key? }] } — key is 'blocks' | 'left' | 'right'
  let list = page.sections[path.section].blocks;
  for (const step of path.chain) list = list[step.index][step.key];
  return list;
}
function blockAt(page, path) {
  const list = path.chain.length
    ? containerAt(page, { section: path.section, chain: path.chain.slice(0, -1) })
    : page.sections[path.section].blocks;
  const last = path.chain.length ? path.chain[path.chain.length - 1] : null;
  return last ? list[last.index] : null;
}
const samePath = (a, b) => JSON.stringify(a) === JSON.stringify(b);

/* ---------- outline ---------- */

function renderOutline() {
  const wrap = $('#outline');
  wrap.textContent = '';

  const pageList = el('div', { className: 'pages' });
  state.content.pages.forEach((page, i) => {
    const row = el('button', {
      className: 'page-tab' + (i === state.sel.page ? ' is-on' : ''),
      type: 'button',
      textContent: page.slug,
      onclick: () => { state.sel = { page: i, path: null }; render(); },
    });
    pageList.append(row);
  });
  pageList.append(el('button', {
    className: 'page-tab page-tab--add', type: 'button', textContent: '+ Page',
    onclick: addPage,
  }));
  wrap.append(pageList);

  const page = state.content.pages[state.sel.page];
  if (!page) return;

  wrap.append(el('div', { className: 'page-meta' }, [
    field('Address', page.slug, (v) => { page.slug = v; touch(); }, { hint: 'lowercase, no spaces — becomes ' + page.slug + '.html' }),
    field('Browser tab title', page.title || '', (v) => { page.title = v; touch(); }),
    field('Hero title', page.hero ? page.hero.title : '', (v) => {
      if (!page.hero) page.hero = { variant: 'page', title: v }; else page.hero.title = v;
      touch();
    }),
    field('Hero eyebrow', page.hero ? page.hero.kicker || '' : '', (v) => {
      if (page.hero) page.hero.kicker = v; touch();
    }),
  ]));

  (page.sections || []).forEach((section, si) => {
    const box = el('div', { className: 'section-box' });
    box.append(el('div', { className: 'section-head' }, [
      el('span', { className: 'section-name', textContent: 'Section ' + (si + 1) }),
      toggle('Tinted', section.tint, (v) => { section.tint = v; touch(); }),
      toggle('Dark', section.dark, (v) => { section.dark = v; touch(); }),
      toggle('Narrow', section.narrow, (v) => { section.narrow = v; touch(); }),
      toggle('Tight', section.tight, (v) => { section.tight = v; touch(); }),
      el('button', { className: 'x', type: 'button', textContent: '✕', title: 'Delete this section',
        onclick: () => removeSection(si) }),
    ]));
    box.append(blockList(page, { section: si, chain: [] }, section.blocks || []));
    wrap.append(box);
  });

  wrap.append(el('button', {
    className: 'add-section', type: 'button', textContent: '+ Add section',
    onclick: () => { page.sections = page.sections || []; page.sections.push({ blocks: [] }); touch(); },
  }));
}

function blockList(page, basePath, blocks) {
  const list = el('div', { className: 'block-list' });
  blocks.forEach((block, bi) => {
    const path = { section: basePath.section, chain: basePath.chain.concat([{ index: bi, key: 'blocks' }]) };
    const label = BLOCK_LABELS[block.type] ? BLOCK_LABELS[block.type][0] : block.type;
    const row = el('div', { className: 'block-row' + (samePath(path, state.sel.path) ? ' is-on' : '') });
    row.append(el('button', {
      className: 'block-name', type: 'button',
      textContent: label + summarise(block),
      onclick: () => { state.sel = { page: state.sel.page, path }; render(); },
    }));
    row.append(el('button', { className: 'mv', type: 'button', textContent: '↑', title: 'Move up',
      disabled: bi === 0, onclick: () => move(blocks, bi, -1) }));
    row.append(el('button', { className: 'mv', type: 'button', textContent: '↓', title: 'Move down',
      disabled: bi === blocks.length - 1, onclick: () => move(blocks, bi, 1) }));
    row.append(el('button', { className: 'x', type: 'button', textContent: '✕', title: 'Delete this block',
      onclick: () => { blocks.splice(bi, 1); state.sel.path = null; touch(); } }));
    list.append(row);

    /* A container's children are nested in the outline, which is the only place
       the structure is visible — the preview shows the result, not the shape. */
    if (block.type === 'group') {
      list.append(el('div', { className: 'nest' },
        blockList(page, { section: basePath.section, chain: path.chain }, block.blocks || [])));
      list.append(nestAdd(block, 'blocks', 'block inside this group'));
    } else if (block.type === 'split') {
      for (const side of ['left', 'right']) {
        list.append(el('div', { className: 'nest' }, [
          el('div', { className: 'nest-label', textContent: side + ' column' }),
          blockList(page, { section: basePath.section, chain: path.chain.slice(0, -1).concat([{ index: bi, key: side }]) },
                    block[side] || []),
          nestAdd(block, side, side + ' column'),
        ]));
      }
    }
  });
  list.append(addBlockButton(blocks));
  return list;
}

function nestAdd(block, key, what) {
  block[key] = block[key] || [];
  return addBlockButton(block[key], 'Add a ' + what);
}

function addBlockButton(target, label) {
  const wrap = el('div', { className: 'add-block' });
  const select = el('select', { className: 'add-select' });
  select.append(el('option', { value: '', textContent: label || '+ Add block' }));
  for (const [type, [name, hint]] of Object.entries(BLOCK_LABELS)) {
    select.append(el('option', { value: type, textContent: name + ' — ' + hint }));
  }
  select.onchange = () => {
    if (!select.value) return;
    target.push(BLOCK_DEFAULTS[select.value]());
    select.value = '';
    touch();
  };
  wrap.append(select);
  return wrap;
}

/* A few words from the block itself, so the outline is scannable without
   clicking every row to find out which paragraph is which. */
function summarise(block) {
  const first = block.title || block.text || block.heading ||
                (Array.isArray(block.items) && block.items.length
                  ? (typeof block.items[0] === 'string' ? block.items[0] : block.items[0].title || block.items[0].label || block.items[0].name || '')
                  : '');
  const text = String(first || '').replace(/\s+/g, ' ').trim();
  return text ? ' · ' + (text.length > 34 ? text.slice(0, 34) + '…' : text) : '';
}

function move(list, index, delta) {
  const target = index + delta;
  if (target < 0 || target >= list.length) return;
  const [item] = list.splice(index, 1);
  list.splice(target, 0, item);
  state.sel.path = null;
  touch();
}

function removeSection(index) {
  state.content.pages[state.sel.page].sections.splice(index, 1);
  state.sel.path = null;
  touch();
}

function addPage() {
  const slug = prompt('Address for the new page (lowercase, no spaces):', 'new-page');
  if (!slug) return;
  state.content.pages.push({
    slug: slug.trim().toLowerCase(),
    navHref: slug.trim().toLowerCase() + '.html',
    title: 'New page',
    hero: { variant: 'page', kicker: '', title: 'New page' },
    sections: [{ blocks: [] }],
  });
  state.sel = { page: state.content.pages.length - 1, path: null };
  touch();
}

/* ---------- the block editor ---------- */

function renderEditor() {
  const wrap = $('#editor');
  wrap.textContent = '';
  if (!state.sel.path) {
    wrap.append(el('p', { className: 'empty', textContent: 'Pick a block on the left to edit it.' }));
    return;
  }
  const page = state.content.pages[state.sel.page];
  const block = blockAt(page, state.sel.path);
  if (!block) { state.sel.path = null; return; }

  const [name, hint] = BLOCK_LABELS[block.type] || [block.type, ''];
  wrap.append(el('h2', { textContent: name }));
  wrap.append(el('p', { className: 'hint', textContent: hint }));

  for (const spec of FIELDS[block.type] || []) {
    wrap.append(renderField(block, spec));
  }
  if (state.focusItem !== null) {
    const fresh = $('.item--new', wrap);
    state.focusItem = null;
    if (fresh) {
      fresh.scrollIntoView({ block: 'center' });
      const first = $('input, textarea', fresh);
      if (first) first.focus();
    }
  }
}

function renderField(obj, spec) {
  if (spec.kind === 'items') return renderItems(obj, spec);
  const value = obj[spec.key];

  if (spec.kind === 'check') return toggle(spec.label, value, (v) => { obj[spec.key] = v; touch(); }, true);

  if (spec.kind === 'select') {
    const sel = el('select', { className: 'input' });
    for (const opt of spec.options) {
      sel.append(el('option', { value: opt, textContent: opt === '' ? '(default)' : opt, selected: (value || '') === opt }));
    }
    sel.onchange = () => { if (sel.value) obj[spec.key] = sel.value; else delete obj[spec.key]; touch(); };
    return labelled(spec, sel);
  }

  if (spec.kind === 'long') {
    const ta = el('textarea', { className: 'input', rows: 4, value: value || '' });
    ta.oninput = () => { obj[spec.key] = ta.value; touch(false); };
    return labelled(spec, ta);
  }

  if (spec.kind === 'number') {
    const input = el('input', { className: 'input', type: 'number', value: value ?? '', min: spec.min, max: spec.max });
    input.oninput = () => { obj[spec.key] = input.value === '' ? undefined : Number(input.value); touch(false); };
    return labelled(spec, input);
  }

  const input = el('input', { className: 'input', type: 'text', value: value || '' });
  input.oninput = () => { obj[spec.key] = input.value; touch(false); };
  const row = labelled(spec, input);
  if (spec.kind === 'image') row.append(uploadButton(input, obj, spec.key));
  return row;
}

function renderItems(block, spec) {
  const box = el('div', { className: 'items' });
  box.append(el('div', { className: 'items-head', textContent: spec.label }));
  const list = block[spec.key] = block[spec.key] || [];

  list.forEach((item, i) => {
    const card = el('div', { className: 'item' + (state.focusItem === i ? ' item--new' : '') });
    card.append(el('div', { className: 'item-head' }, [
      el('span', { textContent: '#' + (i + 1) }),
      el('button', { className: 'mv', type: 'button', textContent: '↑', disabled: i === 0,
        onclick: () => move(list, i, -1) }),
      el('button', { className: 'mv', type: 'button', textContent: '↓', disabled: i === list.length - 1,
        onclick: () => move(list, i, 1) }),
      el('button', { className: 'x', type: 'button', textContent: '✕',
        onclick: () => { list.splice(i, 1); touch(); } }),
    ]));

    if (spec.simple) {
      // A plain list of strings (the bulleted list), not objects.
      const input = el('input', { className: 'input', type: 'text', value: item || '' });
      input.oninput = () => { list[i] = input.value; touch(false); };
      card.append(input);
    } else {
      for (const sub of spec.fields) {
        if (sub.lines) {
          /* iconRows: hide the spans structure behind one text box, but only when
             the row is simple enough to survive the round trip. */
          if (!isSimpleLines(item.lines)) {
            card.append(el('p', { className: 'hint',
              textContent: 'This row contains a link or bold text and is edited in the content file.' }));
            continue;
          }
          const input = el('input', { className: 'input', type: 'text', value: linesToText(item.lines) });
          input.oninput = () => { item.lines = textToLines(input.value); touch(false); };
          card.append(labelled(sub, input));
          continue;
        }
        card.append(renderField(item, sub));
      }
    }
    box.append(card);
  });

  box.append(el('button', {
    className: 'add-item', type: 'button', textContent: '+ Add ' + (ITEM_NOUN[spec.label] || 'another'),
    onclick: () => {
      list.push(spec.simple ? '' : {});
      state.focusItem = list.length - 1;   // renderEditor focuses the new row's first box
      touch();
    },
  }));
  return box;
}

/* "+ Add event", not "+ Add": the officer is adding a thing they have a word for. */
const ITEM_NOUN = { Events: 'event', Cards: 'card', Photos: 'photo', Officers: 'officer',
                    Buttons: 'button', Points: 'point', Rows: 'row' };

function labelled(spec, control) {
  const row = el('label', { className: 'field' }, [
    el('span', { className: 'field-label', textContent: spec.label + (spec.required ? ' *' : '') }),
    control,
  ]);
  if (spec.hint) row.append(el('span', { className: 'field-hint', textContent: spec.hint }));
  return row;
}

function field(label, value, onInput, opts = {}) {
  const input = el('input', { className: 'input', type: 'text', value: value || '' });
  input.oninput = () => onInput(input.value);
  return labelled({ label, hint: opts.hint }, input);
}

function toggle(label, value, onChange, block) {
  const input = el('input', { type: 'checkbox', checked: !!value });
  input.onchange = () => onChange(input.checked);
  return el('label', { className: block ? 'field field--check' : 'chip' }, [input, el('span', { textContent: label })]);
}

function uploadButton(input, obj, key) {
  const picker = el('input', { type: 'file', accept: 'image/*', className: 'hidden-file' });
  const button = el('button', { className: 'upload', type: 'button', textContent: 'Upload…',
    onclick: () => picker.click() });
  picker.onchange = async () => {
    const file = picker.files && picker.files[0];
    if (!file) return;
    button.textContent = 'Uploading…';
    button.disabled = true;
    try {
      const form = new FormData();
      form.append('file', file);
      form.append('dest', 'site');
      const res = await fetch('../api/upload', { method: 'POST', body: form });
      const body = await res.json();
      if (!res.ok || !body.ok) throw new Error(body.error || 'Upload failed.');
      input.value = body.path;
      obj[key] = body.path;
      touch();
    } catch (e) {
      alert('That photo could not be uploaded. ' + (e.message || ''));
    } finally {
      button.textContent = 'Upload…';
      button.disabled = false;
    }
  };
  return el('span', { className: 'upload-wrap' }, [button, picker]);
}

/* ---------- preview ---------- */

function renderPreview() {
  const page = state.content.pages[state.sel.page];
  if (!page) return;
  let html;
  try {
    html = renderPage(page, state.site, { edit: true });
  } catch (e) {
    html = '<p style="font:15px sans-serif;padding:24px">This page can’t be previewed yet: ' + e.message + '</p>';
  }
  /* srcdoc has no document URL, so every relative path in the page would break.
     A <base> pointing at the site root fixes them all in one line. */
  const frame = $('#preview');
  // Re-rendering replaces the document; without this every keystroke jumps the preview to the top.
  const y = frame.contentWindow ? frame.contentWindow.scrollY : 0;
  frame.onload = () => { frame.contentWindow.scrollTo(0, y); wirePreview(frame.contentDocument); };
  frame.srcdoc = html.replace('<head>', '<head><base href="' + new URL('..', location.href).href + '">');
}

/* Click-to-edit on the page itself (the Bound at the Seams editor's model). Every block in the
   preview carries data-edit = the same path the outline uses (js/blocks.js editor mode), so a
   click just selects that block and opens its form. The blocks render with display:contents,
   which has no box of its own, so the hover outline is drawn from the union of the children. */
function wirePreview(doc) {
  if (!doc || !doc.body) return;
  const box = doc.createElement('div');
  box.style.cssText = 'position:absolute;pointer-events:none;border:2px solid #c99a2e;border-radius:6px;' +
    'background:rgba(201,154,46,.08);z-index:2147483646;display:none';
  const tag = doc.createElement('div');
  tag.style.cssText = 'position:absolute;pointer-events:none;background:#c99a2e;color:#fff;font:600 12px/1 sans-serif;' +
    'padding:5px 8px;border-radius:4px;z-index:2147483647;display:none';
  doc.body.append(box, tag);

  const target = (ev) => ev.target && ev.target.closest ? ev.target.closest('[data-edit]') : null;
  const rectOf = (node) => {
    const kids = node.classList.contains('wcaa-edit-empty') ? [node] : [...node.children];
    const rs = kids.map((k) => k.getBoundingClientRect()).filter((r) => r.width || r.height);
    if (!rs.length) return null;
    const x = Math.min(...rs.map((r) => r.left)), yy = Math.min(...rs.map((r) => r.top));
    return { x, y: yy, w: Math.max(...rs.map((r) => r.right)) - x, h: Math.max(...rs.map((r) => r.bottom)) - yy };
  };
  doc.addEventListener('mouseover', (ev) => {
    const node = target(ev);
    const r = node && rectOf(node);
    if (!r) { box.style.display = tag.style.display = 'none'; return; }
    const sx = doc.defaultView.scrollX, sy = doc.defaultView.scrollY;
    Object.assign(box.style, { display: 'block', left: r.x + sx - 4 + 'px', top: r.y + sy - 4 + 'px',
      width: r.w + 8 + 'px', height: r.h + 8 + 'px' });
    const type = node.getAttribute('data-edit-type');
    tag.textContent = '✎ Edit ' + (BLOCK_LABELS[type] ? BLOCK_LABELS[type][0].toLowerCase() : 'this');
    Object.assign(tag.style, { display: 'block', left: r.x + sx - 4 + 'px', top: Math.max(0, r.y + sy - 26) + 'px' });
  });
  // Capture phase: a click on a link or button in the preview edits it instead of following it.
  doc.addEventListener('click', (ev) => {
    const node = target(ev);
    ev.preventDefault();
    ev.stopPropagation();
    if (!node) return;
    let path;
    try { path = JSON.parse(node.getAttribute('data-edit')); } catch { return; }
    state.sel = { page: state.sel.page, path };
    renderOutline();
    renderEditor();
    const on = $('#outline .block-row.is-on');
    if (on) on.scrollIntoView({ block: 'nearest' });
    $('#editor').scrollTop = 0;
  }, true);
  doc.addEventListener('submit', (ev) => ev.preventDefault(), true);
}

/* ---------- saving ---------- */

function touch(full = true) {
  state.dirty = true;
  state.note = '';
  state.error = '';
  $('#save').disabled = false;
  updateStatus();
  if (full) render(); else renderPreview();
}

function updateStatus() {
  const check = validateContent(state.content);
  const status = $('#status');
  if (!check.ok) {
    status.className = 'status status--bad';
    status.textContent = describe(check.path) + ' ' + check.error;
    $('#save').disabled = true;
    return;
  }
  /* After a save, keep saying what happened ("…live in about a minute") until the next edit —
     the old code overwrote it with "Everything is saved." in the same tick, so no officer ever
     saw that the live site lags the save. */
  if (state.error) {
    status.className = 'status status--bad';
    status.textContent = state.error;
    $('#save').disabled = state.saving;
    return;
  }
  status.className = 'status' + (state.dirty ? ' status--dirty' : state.note ? ' status--good' : '');
  status.textContent = state.dirty ? 'You have unsaved changes.' : state.note || 'Everything is saved.';
  $('#save').disabled = !state.dirty || state.saving;
}

/* "pages[0].sections[2].blocks[0].left[1].items[0]" -> "Home page, an item in a block:"
   An officer can't act on an array path; they can act on "which page". */
function describe(path) {
  const m = /^pages\[(\d+)\]/.exec(path || '');
  const page = m && state.content.pages[Number(m[1])];
  if (!page) return path || '';
  const where = /items\[\d+\]$/.test(path) ? 'one of the items' : 'a block';
  return 'On the “' + page.slug + '” page, ' + where;
}

async function saveSite() {
  if (state.saving) return;
  state.saving = true;
  $('#save').disabled = true;
  $('#save').textContent = 'Saving…';
  try {
    const res = await fetch('../api/save', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ content: state.content, site: state.site, base: state.base }),
    });
    const body = await res.json();
    if (res.status === 401) { showSignIn(); return; }
    if (!res.ok || !body.ok) throw new Error(body.error || 'Save failed.');
    if (body.base) state.base = body.base;   // what the branch now holds, so the next save passes
    state.dirty = false;
    state.note = body.note || 'Saved.';
  } catch (e) {
    state.error = e.message;   // shown by updateStatus until the next edit (was overwritten at once)
  } finally {
    state.saving = false;
    $('#save').textContent = 'Save changes';
    updateStatus();
  }
}

/* ---------- sign in ---------- */

function showSignIn() { $('#signin').hidden = false; $('#app').hidden = true; }
function showApp() { $('#signin').hidden = true; $('#app').hidden = false; }

async function signIn(event) {
  event.preventDefault();
  const error = $('#signin-error');
  error.textContent = '';
  const res = await fetch('../api/login', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ username: $('#username').value, password: $('#password').value }),
  });
  const body = await res.json().catch(() => ({}));
  if (!res.ok || !body.ok) { error.textContent = body.error || 'That didn’t work.'; return; }
  await start();
}

/* ---------- boot ---------- */

/* ---------- events & registrations (D1, NOT content) ----------
   Content is the public site (committed, world-readable). This is registration
   STATE for the events that take RSVPs — it lives in D1, never touches the repo
   (see functions/api/rsvp.js). Opening an event here is what lets the public RSVP
   form on the Events page accept sign-ups; the form binds to the event's id. */

function setMode(m) {
  const content = m === 'content';
  $('.cols').hidden = !content;
  $('#events-view').hidden = content;
  $('#mode-content').classList.toggle('is-on', content);
  $('#mode-events').classList.toggle('is-on', !content);
  $('#save').hidden = !content;      // "Save changes" is the content editor's; irrelevant here
  $('#status').hidden = !content;
  if (!content) loadEvents();
}

async function loadEvents() {
  const view = $('#events-view');
  view.textContent = '';
  view.append(el('div', { className: 'ev-intro' }, [
    el('h2', { className: 'ev-h', textContent: 'Event registration' }),
    el('p', { className: 'hint', textContent: 'Open an event here so the RSVP form on the Events page can take sign-ups. The form binds to the event’s id — use that same id in the Upcoming Event block on the Events page.' }),
  ]));
  view.append(openForm());
  const list = el('div', { className: 'ev-list', textContent: 'Loading…' });
  view.append(list);
  let events = [];
  try { const r = await fetch('../api/events').then((x) => x.json()); events = r.ok ? r.events : []; }
  catch { list.textContent = 'Couldn’t load events.'; return; }
  list.textContent = '';
  if (!events.length) { list.append(el('p', { className: 'empty', textContent: 'No events yet — open registration for one above.' })); return; }
  events.forEach((ev) => list.append(eventCard(ev)));
}

function evField(label, control, hint) {
  const kids = [el('span', { className: 'field-label', textContent: label }), control];
  if (hint) kids.push(el('span', { className: 'field-hint', textContent: hint }));
  return el('label', { className: 'field' }, kids);
}

function openForm() {
  const id = el('input', { className: 'input', placeholder: '2026-10-roman-shade', required: true });
  const title = el('input', { className: 'input', placeholder: 'Roman Shade Workshop', required: true });
  const cap = el('input', { className: 'input', type: 'number', min: '1', placeholder: 'no limit' });
  const msg = el('p', { className: 'ev-msg' });
  const form = el('form', { className: 'ev-open' }, [
    el('div', { className: 'ev-open-row' }, [
      evField('Event id', id, 'lowercase, no spaces — the public form binds to this'),
      evField('Title', title),
      evField('Capacity', cap, 'total seats incl. guests; blank = unlimited'),
    ]),
    el('div', { className: 'ev-open-actions' }, [
      el('button', { className: 'btn btn--primary', type: 'submit', textContent: 'Open registration' }),
      msg,
    ]),
  ]);
  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    const body = { id: id.value.trim(), title: title.value.trim() };
    if (cap.value.trim()) body.capacity = Number(cap.value.trim());
    msg.textContent = 'Opening…'; msg.className = 'ev-msg';
    let r;
    try { r = await fetch('../api/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }).then((x) => x.json()); }
    catch { msg.textContent = 'Network error — try again.'; msg.className = 'ev-msg ev-msg--bad'; return; }
    if (!r.ok) { msg.textContent = r.error || 'Couldn’t open it.'; msg.className = 'ev-msg ev-msg--bad'; return; }
    id.value = ''; title.value = ''; cap.value = ''; msg.textContent = '';
    loadEvents();
  });
  return form;
}

function eventCard(ev) {
  const seats = ev.seats || 0;
  const closed = !!ev.closed;
  const badge = el('span', { className: 'ev-badge ' + (closed ? 'ev-badge--closed' : 'ev-badge--open'), textContent: closed ? 'Closed' : 'Open' });
  const count = el('span', { className: 'ev-seats', textContent: ev.capacity ? `${seats} / ${ev.capacity} seats` : `${seats} seat${seats === 1 ? '' : 's'}` });
  const toggle = el('button', { className: 'ev-btn', type: 'button', textContent: closed ? 'Reopen' : 'Close' });
  toggle.addEventListener('click', async () => {
    toggle.disabled = true;
    try { await fetch('../api/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: ev.id, title: ev.title, capacity: ev.capacity, closed: closed ? 0 : 1 }) }); } catch {}
    loadEvents();
  });
  const box = el('div', { className: 'ev-rsvps', hidden: true });
  const view = el('button', { className: 'ev-btn', type: 'button', textContent: `Sign-ups (${seats})` });
  view.addEventListener('click', () => { box.hidden = !box.hidden; if (!box.hidden) loadRsvps(ev, box); });
  // Delete only an empty event — the server refuses otherwise (rsvps cascade), so
  // the button mirrors that: disabled while anyone is signed up.
  const del = el('button', { className: 'ev-btn ev-btn--danger', type: 'button', textContent: 'Delete' });
  if (seats > 0) { del.disabled = true; del.title = 'Remove the sign-ups first.'; }
  del.addEventListener('click', async () => {
    if (!confirm(`Delete “${ev.title}”? This can’t be undone.`)) return;
    del.disabled = true;
    let res;
    try { res = await fetch('../api/events/delete', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: ev.id }) }).then((x) => x.json()); }
    catch { res = { ok: false, error: 'Network error.' }; }
    if (!res.ok) { del.disabled = false; alert(res.error || 'Couldn’t delete that event.'); return; }
    loadEvents();
  });
  return el('div', { className: 'ev-card' }, [
    el('div', { className: 'ev-card-head' }, [
      el('div', { className: 'ev-card-title' }, [el('span', { className: 'ev-name', textContent: ev.title }), el('code', { className: 'ev-id', textContent: ev.id })]),
      badge, count,
      el('div', { className: 'ev-actions' }, [view, toggle, del]),
    ]),
    box,
  ]);
}

async function loadRsvps(ev, box) {
  box.textContent = 'Loading…';
  let data;
  try { data = await fetch('../api/rsvps?event_id=' + encodeURIComponent(ev.id)).then((x) => x.json()); }
  catch { box.textContent = 'Couldn’t load sign-ups.'; return; }
  const rsvps = data.ok ? data.rsvps : [];
  box.textContent = '';
  const csv = el('a', { className: 'ev-btn ev-btn--sm', href: '../api/rsvps?format=csv&event_id=' + encodeURIComponent(ev.id), textContent: 'Export CSV' });
  box.append(el('div', { className: 'ev-rsvps-head' }, [el('span', { textContent: `${rsvps.length} sign-up${rsvps.length === 1 ? '' : 's'}` }), rsvps.length ? csv : el('span')]));
  if (!rsvps.length) { box.append(el('p', { className: 'empty', textContent: 'No sign-ups yet.' })); return; }
  rsvps.forEach((r) => box.append(rsvpRow(r, ev, box)));
}

function rsvpRow(r, ev, box) {
  const guests = r.guests ? ` +${r.guests}` : '';
  const del = el('button', { className: 'ev-x', type: 'button', title: 'Remove this registration', textContent: '✕' });
  del.addEventListener('click', async () => {
    if (!confirm(`Remove ${r.name}’s registration?`)) return;
    del.disabled = true;
    let res;
    try { res = await fetch('../api/rsvps/delete', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: r.id }) }).then((x) => x.json()); }
    catch { del.disabled = false; return; }
    if (res.ok) loadRsvps(ev, box); else { del.disabled = false; alert(res.error || 'Couldn’t remove it.'); }
  });
  return el('div', { className: 'ev-rsvp' }, [
    el('div', { className: 'ev-rsvp-main' }, [
      el('span', { className: 'ev-rsvp-name', textContent: r.name + guests }),
      el('a', { className: 'ev-rsvp-email', href: 'mailto:' + r.email, textContent: r.email }),
    ]),
    el('span', { className: 'ev-rsvp-meta', textContent: [r.phone, r.business].filter(Boolean).join(' · ') }),
    del,
  ]);
}

function render() {
  renderOutline();
  renderEditor();
  renderPreview();
  updateStatus();
}

async function start() {
  await loadSite();
  showApp();
  render();
}

window.addEventListener('beforeunload', (e) => {
  if (state.dirty) { e.preventDefault(); e.returnValue = ''; }
});

$('#signin-form').addEventListener('submit', signIn);
$('#save').addEventListener('click', saveSite);
$('#mode-content').addEventListener('click', () => setMode('content'));
$('#mode-events').addEventListener('click', () => setMode('events'));

/* The session cookie is HttpOnly, so the page cannot read it. /api/session is the
   honest way to ask — rather than probing some other endpoint and inferring the
   answer from which error it returns. */
fetch('../api/session')
  .then((r) => (r.ok ? start() : showSignIn()))
  .catch(showSignIn);
