/* The website editor. Vanilla ES modules, no framework, no build step — same as the
   rest of this repo, and for the same reason: a chapter officer's website should
   still be editable in five years without anyone reinstalling a toolchain.

   HOW IT WORKS (the Bound at the Seams model): the officer sees the real page, full width,
   rendered by js/blocks.js — the SAME module the Worker runs at save time, so what they see
   before saving is generated by the identical code that generates what ships. Words are typed
   straight into the page; a photo, a button or an event opens a short panel for just that one
   thing. Nothing is sent until the one Save button, which commits through /api/save.

   ⛔ NOTHING HERE IS A SECURITY CONTROL. Every check in this file is a courtesy to
   the person using it. The real validation is functions/api/save.js, which does
   not trust a single byte of what this sends. If the two ever disagree, the
   endpoint is right. */
import { renderPage, pathKey, eventItems } from '../js/blocks.js';
import { validateContent, contentFingerprint } from '../js/validate-content.js';
import { FIELDS, HERO_FIELDS, ADVANCED_KEYS, BLOCK_LABELS, BLOCK_DEFAULTS, linesToText, textToLines, isSimpleLines } from './fields.js';

const $ = (sel, root = document) => root.querySelector(sel);
const el = (tag, props = {}, kids = []) => {
  const node = Object.assign(document.createElement(tag), props);
  for (const kid of [].concat(kids)) node.append(kid);
  return node;
};

const state = {
  content: null, site: null, page: 0,
  pristine: '',        // JSON of what was last loaded or saved: Discard goes back to it
  base: null,          // fingerprint of the stored content, for /api/save's stale-editor check
  links: true,         // false when private meeting links couldn't be loaded (see /api/content)
  dirty: false, saving: false, note: '', error: '', errorPath: null,
  drawer: null,        // { kind: 'item' | 'block', path } | { kind: 'hero' } | { kind: 'layout' }
};

/* What one entry of each list is called, for "Event details", "+ Add another photo"… */
const NOUN = { events: 'event', cards: 'card', gallery: 'photo', officers: 'officer', buttons: 'button',
               list: 'point', iconRows: 'row' };
const ITEM_DEFAULT = { events: () => ({}), cards: () => ({}), gallery: () => ({}), officers: () => ({}),
                       buttons: () => ({ variant: 'primary' }), list: () => '', iconRows: () => ({ lines: [] }) };
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const an = (noun) => (/^[aeiou]/.test(noun) ? 'an ' : 'a ') + noun;

/* ---------- loading ---------- */

const snapshot = () => JSON.stringify({ content: state.content, site: state.site });

async function loadSite() {
  /* Straight from the branch (/api/content), so an officer who saved a minute ago and reopens
     the editor doesn't load the pre-save copy the not-yet-rebuilt site still serves. Falls back
     to the deployed files if that endpoint is unavailable. */
  let content, site, base = null, links = true;
  try {
    const r = await fetch('../api/content', { cache: 'no-store' }).then((x) => x.json());
    if (!r.ok) throw new Error(r.error);
    ({ content, site } = r);
    base = typeof r.base === 'string' ? r.base : null;
    links = r.links !== false;
  } catch {
    const bust = '?t=' + Date.now();
    [content, site] = await Promise.all([
      fetch('../content/pages.json' + bust).then((r) => r.json()),
      fetch('../content/site.json' + bust).then((r) => r.json()),
    ]);
    links = false;
  }
  state.content = content;
  state.site = site;
  state.base = base || await contentFingerprint(content, site);
  state.links = links;
  state.pristine = snapshot();
  state.dirty = false;
}

/* ---------- paths ----------
   Everything on a page is addressed by a dotted path from the page object, the same strings
   js/blocks.js writes into the preview: "hero.title", "sections.1.blocks.0.items.2.title". */

const curPage = () => state.content.pages[state.page];
function getAt(root, path) {
  if (!path) return root;
  return path.split('.').reduce((o, k) => (o === null || o === undefined ? undefined : o[k]), root);
}
function setAt(root, path, value) {
  const i = path.lastIndexOf('.');
  const parent = getAt(root, path.slice(0, i));
  if (parent && typeof parent === 'object') parent[path.slice(i + 1)] = value;
}
const parentOf = (path) => path.slice(0, path.lastIndexOf('.'));
const lastOf = (path) => path.slice(path.lastIndexOf('.') + 1);

/* ---------- event registration ids ----------
   Minted ONCE, when an event first takes registration, from its date and name, and never
   recomputed — sign-ups are stored against it, so renaming the event must not orphan them.
   The same event listed on two pages (same date and name) shares one id. */
const slugify = (s) => String(s || '').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
function ensureEventIds() {
  const all = eventItems(state.content);
  const key = (e) => [e.month, e.day, e.title].map((x) => String(x || '').trim().toLowerCase()).join('|');
  for (const e of all) {
    const wants = e.register === true || (typeof e.meetingLink === 'string' && e.meetingLink.trim());
    if (!wants || e.id || !String(e.title || '').trim()) continue;
    const twin = all.find((o) => o !== e && o.id && key(o) === key(e));
    if (twin) { e.id = twin.id; continue; }
    const base = slugify([e.month, e.day, e.title].filter(Boolean).join(' ')).slice(0, 56).replace(/-+$/, '') || 'event';
    let id = base, n = 2;
    while (all.some((o) => o !== e && o.id === id)) id = base + '-' + n++;
    e.id = id;
  }
}

/* ---------- after every change ---------- */

let previewTimer = null;
function changed({ preview = true, drawer = false, now = false } = {}) {
  ensureEventIds();
  state.dirty = snapshot() !== state.pristine;   // typing a word and deleting it again is "no change"
  state.note = '';
  state.error = '';
  updateStatus();
  if (drawer) renderDrawer();
  if (preview) {
    clearTimeout(previewTimer);
    // Typing in a panel redraws the page a beat later, not on every key.
    if (now) renderPreview(); else previewTimer = setTimeout(renderPreview, 250);
  }
}

function updateStatus() {
  const check = validateContent(state.content);
  const status = $('#status');
  state.errorPath = null;
  if (!check.ok) {
    status.className = 'status status--bad';
    status.textContent = describe(check.path) + ' ' + check.error;
    state.errorPath = check.path;
  } else if (state.error) {
    status.className = 'status status--bad';
    status.textContent = state.error;
  } else {
    status.className = 'status' + (state.dirty ? ' status--dirty' : state.note ? ' status--good' : '');
    status.textContent = state.dirty ? 'You have changes that aren’t saved yet.' : state.note || 'Everything is saved.';
  }
  $('#save').disabled = !check.ok || !state.dirty || state.saving;
  $('#discard').disabled = !state.dirty || state.saving;
}

/* "pages[2].sections[0].blocks[1].items[3].meetingLink" -> "On the Events page, “Fall Tour”:"
   An officer can't act on an array path; they can act on "which page, which event". */
function describe(path) {
  const dotted = String(path || '').replace(/\[(\d+)\]/g, '.$1');
  const m = /^pages\.(\d+)/.exec(dotted);
  const page = m && state.content.pages[Number(m[1])];
  if (!page) return '';
  const item = /^(.*\.items\.\d+)/.exec(dotted);
  const thing = item && getAt(state.content, item[1]);
  const name = thing && (thing.title || thing.name || thing.label);
  return 'On the ' + pageName(state.content.pages.indexOf(page)) + ' page' + (name ? ', “' + name + '”' : '') + ':';
}

function pageName(i) {
  const page = state.content.pages[i];
  const nav = (state.site.nav || []).find((l) => l && l.href === page.navHref);
  return (nav && nav.label) || (page.slug === 'index' ? 'Home' : (page.hero && page.hero.title) || page.slug);
}

/* ---------- the page itself ---------- */

const EDITOR_CSS = `
[data-f]{outline:2px dashed rgba(169,127,47,.6);outline-offset:3px;border-radius:2px;cursor:text;min-width:2ch}
[data-f]:hover{outline-color:#7c5a1e}
[data-f]:focus{outline:3px solid #0e57a0;outline-offset:3px;background:rgba(255,236,170,.5)}
[data-f]:empty::before{content:'Type here';color:#5f6a78}
[data-item],[data-hero],[data-edit-type=image],[data-edit-type=gallery],[data-edit-type=buttons],[data-edit-type=iconRows]{cursor:pointer}
.wcaa-edit-details{display:inline-flex;align-items:center;align-self:flex-start;min-height:48px;margin-top:12px;padding:0 18px;
  font:600 18px/1 system-ui,-apple-system,"Segoe UI",sans-serif;color:#fff;background:#0e57a0;border:0;border-radius:8px;cursor:pointer}
.wcaa-edit-details--hero{position:absolute;top:16px;right:16px;z-index:5;margin:0;box-shadow:0 2px 8px rgba(0,0,0,.3)}
.wcaa-edit-details:focus-visible,.wcaa-edit-add:focus-visible{outline:3px solid #bf9a4a;outline-offset:2px}
.wcaa-edit-add{display:block;width:100%;margin:16px 0 0;min-height:52px;padding:0 20px;font:600 18px/1 system-ui,-apple-system,"Segoe UI",sans-serif;
  color:#5c4316;background:#fdf8ec;border:2px dashed #a97f2f;border-radius:10px;cursor:pointer}
`;

function renderPreview() {
  clearTimeout(previewTimer);
  const page = curPage();
  if (!page) return;
  let html;
  try {
    html = renderPage(page, state.site, { edit: true });
  } catch (e) {
    html = '<p style="font:18px sans-serif;padding:24px">This page can’t be shown yet: ' + e.message + '</p>';
  }
  /* srcdoc has no document URL, so every relative path in the page would break.
     A <base> pointing at the site root fixes them all in one line. */
  const frame = $('#preview');
  // Re-rendering replaces the document; keep the officer's place on the page.
  const y = frame.contentWindow ? frame.contentWindow.scrollY : 0;
  frame.onload = () => { frame.contentWindow.scrollTo(0, y); wirePreview(frame.contentDocument); };
  frame.srcdoc = html.replace('<head>', '<head><base href="' + new URL('..', location.href).href + '">');
}

function wirePreview(doc) {
  if (!doc || !doc.body) return;
  doc.head.append(Object.assign(doc.createElement('style'), { textContent: EDITOR_CSS }));

  /* plaintext-only where the browser has it: pasted or typed formatting can't sneak in. The
     model only ever stores the text (textContent) either way. */
  let mode = 'true';
  try { const t = doc.createElement('div'); t.contentEditable = 'plaintext-only'; if (t.contentEditable === 'plaintext-only') mode = 'plaintext-only'; } catch {}
  for (const n of doc.querySelectorAll('[data-f]')) {
    n.contentEditable = mode;
    n.spellcheck = true;
    n.setAttribute('role', 'textbox');
    n.setAttribute('aria-label', 'Change this text');
  }

  /* Every event, card and officer gets a visible "… details" button. Clicking its words types
     into them, so without the button there'd be nowhere obvious to click for the date, the
     registration switch or the meeting link — and nothing here may depend on hovering. */
  for (const n of doc.querySelectorAll('[data-item]')) {
    if (!n.querySelector('[data-f]')) continue;
    const type = blockTypeOfItem(n.getAttribute('data-item'));
    const b = doc.createElement('button');
    b.type = 'button';
    b.className = 'wcaa-edit-details';
    b.setAttribute('data-open', n.getAttribute('data-item'));
    b.textContent = '✎ ' + cap(NOUN[type] || 'item') + ' details';
    (n.querySelector('.wcaa-ev__body') || n).append(b);
  }
  const hero = doc.querySelector('[data-hero]');
  if (hero) {
    const b = doc.createElement('button');
    b.type = 'button';
    b.className = 'wcaa-edit-details wcaa-edit-details--hero';
    b.setAttribute('data-open', 'hero');
    b.textContent = '✎ Banner photo and buttons';
    hero.append(b);
  }

  doc.addEventListener('input', (ev) => {
    const n = ev.target && ev.target.closest ? ev.target.closest('[data-f]') : null;
    if (!n) return;
    const path = n.getAttribute('data-f');
    setAt(curPage(), path, n.textContent.replace(/\s*\n\s*/g, ' '));
    changed({ preview: false, drawer: drawerShows(path) });
  });
  doc.addEventListener('keydown', (ev) => {
    if (!ev.target.closest || !ev.target.closest('[data-f]')) return;
    if (ev.key === 'Enter' || ev.key === 'Escape') { ev.preventDefault(); ev.target.blur(); }
  });
  // Pasting from an email or a Word file brings formatting along; keep only the words.
  doc.addEventListener('paste', (ev) => {
    if (!ev.target.closest || !ev.target.closest('[data-f]')) return;
    ev.preventDefault();
    const text = (ev.clipboardData ? ev.clipboardData.getData('text/plain') : '').replace(/\s+/g, ' ');
    doc.execCommand('insertText', false, text);
  });
  doc.addEventListener('drop', (ev) => ev.preventDefault(), true);
  doc.addEventListener('submit', (ev) => ev.preventDefault(), true);

  // Capture phase: links and buttons on the page never navigate while editing.
  doc.addEventListener('click', (ev) => {
    const t = ev.target && ev.target.closest ? ev.target : null;
    ev.preventDefault();
    if (!t) return;
    const add = t.closest('[data-add]');
    if (add) { ev.stopPropagation(); return addItem(add.getAttribute('data-add')); }
    const open = t.closest('[data-open]');
    if (open) {
      ev.stopPropagation();
      const target = open.getAttribute('data-open');
      return openDrawer(target === 'hero' ? { kind: 'hero' } : { kind: 'item', path: target });
    }
    if (t.closest('[data-f]')) return;   // typing in place: the caret is already there
    ev.stopPropagation();
    const item = t.closest('[data-item]');
    if (item) return openDrawer({ kind: 'item', path: item.getAttribute('data-item') });
    if (t.closest('[data-hero]')) return openDrawer({ kind: 'hero' });
    const block = t.closest('[data-edit]');
    if (block) {
      try { openDrawer({ kind: 'block', path: pathKey(JSON.parse(block.getAttribute('data-edit'))) }); } catch {}
    }
  }, true);
}

function blockTypeOfItem(itemPath) {
  const block = getAt(curPage(), parentOf(parentOf(itemPath)));
  return block && block.type;
}

/* Is the open panel showing the field the officer just typed into on the page? */
function drawerShows(fieldPath) {
  const d = state.drawer;
  if (!d) return false;
  if (d.kind === 'hero') return fieldPath.startsWith('hero.');
  if (d.kind === 'item' || d.kind === 'block') return fieldPath.startsWith(d.path + '.');
  return false;
}

/* ---------- adding to a list ---------- */

function addItem(listPath) {
  const page = curPage();
  const block = getAt(page, parentOf(listPath));
  if (!block || !NOUN[block.type]) return;
  block.items = Array.isArray(block.items) ? block.items : [];
  block.items.push(ITEM_DEFAULT[block.type]());
  openDrawer({ kind: 'item', path: listPath + '.' + (block.items.length - 1) }, { focus: true });
  changed({ now: true });
}

/* An entry added and then left completely blank isn't saved as an invisible, empty event. */
function isBlank(v) {
  if (v === null || v === undefined) return true;
  if (typeof v === 'string') return !v.trim();
  if (Array.isArray(v)) return v.every(isBlank);
  if (typeof v === 'object') return Object.keys(v).filter((k) => k !== 'variant').every((k) => isBlank(v[k]));
  return v === false;
}

/* ---------- the side panel ---------- */

function openDrawer(target, { focus = false } = {}) {
  const pruned = pruneBlankItem();
  if (pruned && target.kind === 'item' && parentOf(target.path) === pruned.list) {
    const i = Number(lastOf(target.path));
    if (i === pruned.index) return closeDrawer();
    if (i > pruned.index) target = { kind: 'item', path: pruned.list + '.' + (i - 1) };
  }
  state.drawer = target;
  renderDrawer();
  if (focus) { const first = $('#drawer-body input, #drawer-body textarea'); if (first) first.focus(); }
  else $('#drawer-close').focus();
}

function closeDrawer() {
  pruneBlankItem();
  state.drawer = null;
  renderDrawer();
  changed({ now: true });
}

function pruneBlankItem() {
  const d = state.drawer;
  if (!d || d.kind !== 'item') return null;
  const list = getAt(curPage(), parentOf(d.path));
  const i = Number(lastOf(d.path));
  if (!Array.isArray(list) || i >= list.length || !isBlank(list[i])) return null;
  list.splice(i, 1);
  return { list: parentOf(d.path), index: i };
}

function renderDrawer() {
  const d = state.drawer;
  const drawer = $('#drawer');
  document.body.classList.toggle('has-drawer', !!d);
  if (!d) { drawer.hidden = true; return; }
  const body = $('#drawer-body');
  body.textContent = '';
  let title = '';
  if (d.kind === 'item') title = itemPanel(body, d.path);
  else if (d.kind === 'block') title = blockPanel(body, d.path);
  else if (d.kind === 'hero') title = heroPanel(body);
  else if (d.kind === 'layout') title = layoutPanel(body);
  if (title === null) { state.drawer = null; drawer.hidden = true; document.body.classList.remove('has-drawer'); return; }
  $('#drawer-title').textContent = title;
  drawer.hidden = false;
}

function itemPanel(body, path) {
  const page = curPage();
  const listPath = parentOf(path);
  const index = Number(lastOf(path));
  const block = getAt(page, parentOf(listPath));
  const list = getAt(page, listPath);
  if (!block || !Array.isArray(list) || index >= list.length) return null;
  const item = list[index];
  const spec = (FIELDS[block.type] || []).find((f) => f.kind === 'items');
  const noun = NOUN[block.type] || 'item';
  if (!spec) return null;

  if (spec.simple) {
    const input = el('input', { className: 'input', type: 'text', value: item || '' });
    input.oninput = () => { list[index] = input.value; changed(); };
    body.append(labelled({ label: cap(noun) }, input));
  } else {
    const style = el('details', { className: 'more' }, el('summary', { textContent: 'Style' }));
    for (const sub of spec.fields) {
      if (sub.lines) { body.append(linesField(item, sub)); continue; }
      if (ADVANCED_KEYS.includes(sub.key)) { style.append(renderField(item, sub)); continue; }
      body.append(renderField(item, sub));
      if (block.type === 'events' && sub.key === 'meetingLink' && !state.links) {
        body.append(el('p', { className: 'field-hint field-hint--warn',
          textContent: 'Saved meeting links couldn’t be loaded just now, so this box may look empty even if a link is saved. Leave it empty to keep the saved link.' }));
      }
    }
    if (style.children.length > 1) body.append(style);
  }

  const row = el('div', { className: 'drawer-actions' });
  row.append(el('button', { className: 'btn btn--quiet', type: 'button', textContent: 'Move earlier', disabled: index === 0,
    onclick: () => moveItem(list, listPath, index, -1) }));
  row.append(el('button', { className: 'btn btn--quiet', type: 'button', textContent: 'Move later', disabled: index === list.length - 1,
    onclick: () => moveItem(list, listPath, index, 1) }));
  row.append(el('button', { className: 'btn btn--danger', type: 'button', textContent: 'Remove this ' + noun,
    onclick: () => {
      const name = typeof item === 'string' ? item : item.title || item.name || item.label || item.caption || '';
      if (!confirm('Remove ' + (name ? '“' + name + '”' : 'this ' + noun) + ' from the page? You can still press “Discard changes” before saving.')) return;
      list.splice(index, 1);
      state.drawer = null;
      renderDrawer();
      changed({ now: true });
    } }));
  body.append(row);
  body.append(el('button', { className: 'btn btn--add', type: 'button', textContent: '+ Add another ' + noun,
    onclick: () => addItem(listPath) }));
  body.append(moreSettings(block));
  return cap(noun) + ' details';
}

function moveItem(list, listPath, index, delta) {
  const to = index + delta;
  if (to < 0 || to >= list.length) return;
  const [it] = list.splice(index, 1);
  list.splice(to, 0, it);
  state.drawer = { kind: 'item', path: listPath + '.' + to };
  changed({ drawer: true, now: true });
}

/* Layout settings (spacing, columns, alignment) for the list or block, folded away. */
function moreSettings(block) {
  const specs = (FIELDS[block.type] || []).filter((s) => s.kind !== 'items' && ADVANCED_KEYS.includes(s.key));
  if (!specs.length) return el('span');
  const box = el('details', { className: 'more' });
  box.append(el('summary', { textContent: 'Layout settings (spacing, columns)' }));
  for (const s of specs) box.append(renderField(block, s));
  return box;
}

function blockPanel(body, path) {
  const page = curPage();
  const block = getAt(page, path);
  if (!block || !FIELDS[block.type]) return null;
  const [name, hint] = BLOCK_LABELS[block.type] || [block.type, ''];
  if (hint) body.append(el('p', { className: 'hint', textContent: hint }));

  for (const spec of FIELDS[block.type]) {
    if (ADVANCED_KEYS.includes(spec.key)) continue;
    if (spec.kind !== 'items') { body.append(renderField(block, spec)); continue; }
    // A list: the simple ones edit inline here, the rest list their entries to open one at a time.
    if (spec.simple || block.type === 'iconRows') { body.append(renderItems(block, spec)); continue; }
    const noun = NOUN[block.type] || 'item';
    const box = el('div', { className: 'items' });
    box.append(el('div', { className: 'items-head', textContent: spec.label }));
    (block.items || []).forEach((it, i) => {
      box.append(el('button', { className: 'item-row', type: 'button',
        textContent: (it && (it.title || it.name || it.label || it.caption || it.alt)) || cap(noun) + ' ' + (i + 1),
        onclick: () => openDrawer({ kind: 'item', path: path + '.items.' + i }) }));
    });
    box.append(el('button', { className: 'btn btn--add', type: 'button', textContent: '+ Add ' + an(noun),
      onclick: () => addItem(path + '.items') }));
    body.append(box);
  }
  body.append(moreSettings(block));
  body.append(el('div', { className: 'drawer-actions' }, [
    el('button', { className: 'btn btn--danger', type: 'button', textContent: 'Remove this from the page',
      onclick: () => {
        if (!confirm('Remove this ' + name.toLowerCase() + ' from the page? You can still press “Discard changes” before saving.')) return;
        getAt(page, parentOf(path)).splice(Number(lastOf(path)), 1);
        state.drawer = null;
        renderDrawer();
        changed({ now: true });
      } }),
  ]));
  return name;
}

function heroPanel(body) {
  const page = curPage();
  if (!page.hero) page.hero = { variant: 'page', title: pageName(state.page) };
  for (const spec of HERO_FIELDS) body.append(spec.kind === 'items' ? renderItems(page.hero, spec) : renderField(page.hero, spec));
  return 'Page banner';
}

/* ---------- fields ---------- */

function renderField(obj, spec) {
  if (spec.kind === 'items') return renderItems(obj, spec);
  const value = obj[spec.key];

  if (spec.kind === 'check') {
    const input = el('input', { type: 'checkbox', checked: !!value });
    input.onchange = () => { obj[spec.key] = input.checked; changed({ drawer: true, now: true }); };
    const row = el('label', { className: 'field field--check' }, [input, el('span', { textContent: spec.label })]);
    return spec.hint ? el('div', {}, [row, el('p', { className: 'field-hint', textContent: spec.hint })]) : row;
  }

  if (spec.kind === 'select') {
    const sel = el('select', { className: 'input' });
    for (const opt of spec.options) {
      sel.append(el('option', { value: opt, textContent: opt === '' ? '(standard)' : opt, selected: (value || '') === opt }));
    }
    sel.onchange = () => { if (sel.value) obj[spec.key] = sel.value; else delete obj[spec.key]; changed(); };
    return labelled(spec, sel);
  }

  if (spec.kind === 'long') {
    const ta = el('textarea', { className: 'input', rows: 4, value: value || '' });
    ta.oninput = () => { obj[spec.key] = ta.value; changed(); };
    return labelled(spec, ta);
  }

  if (spec.kind === 'number') {
    const input = el('input', { className: 'input', type: 'number', value: value ?? '', min: spec.min, max: spec.max });
    input.oninput = () => { obj[spec.key] = input.value === '' ? undefined : Number(input.value); changed(); };
    return labelled(spec, input);
  }

  const input = el('input', { className: 'input', type: spec.key === 'meetingLink' ? 'url' : 'text', value: value || '' });
  if (spec.key === 'meetingLink') { input.inputMode = 'url'; input.placeholder = 'https://…'; }
  input.oninput = () => { obj[spec.key] = input.value; changed(); };
  const row = labelled(spec, input);
  if (spec.kind === 'image') row.append(uploadButton(input, obj, spec.key));
  return row;
}

/* A list edited in place (bulleted points, icon rows, a banner's buttons). */
function renderItems(block, spec) {
  const box = el('div', { className: 'items' });
  box.append(el('div', { className: 'items-head', textContent: spec.label }));
  const list = block[spec.key] = block[spec.key] || [];

  list.forEach((item, i) => {
    const card = el('div', { className: 'item' });
    card.append(el('div', { className: 'item-head' }, [
      el('span', { textContent: '#' + (i + 1) }),
      el('button', { className: 'mv', type: 'button', textContent: 'Up', disabled: i === 0,
        onclick: () => { move(list, i, -1); } }),
      el('button', { className: 'mv', type: 'button', textContent: 'Down', disabled: i === list.length - 1,
        onclick: () => { move(list, i, 1); } }),
      el('button', { className: 'mv mv--x', type: 'button', textContent: 'Remove',
        onclick: () => { list.splice(i, 1); changed({ drawer: true, now: true }); } }),
    ]));
    if (spec.simple) {
      const input = el('input', { className: 'input', type: 'text', value: item || '' });
      input.oninput = () => { list[i] = input.value; changed(); };
      card.append(input);
    } else {
      for (const sub of spec.fields) card.append(sub.lines ? linesField(item, sub) : renderField(item, sub));
    }
    box.append(card);
  });

  box.append(el('button', {
    className: 'btn btn--add', type: 'button', textContent: '+ Add ' + an((ITEM_NOUN[spec.label] || 'item')),
    onclick: () => { list.push(spec.simple ? '' : {}); changed({ drawer: true, now: true }); },
  }));
  return box;
}

/* iconRows: hide the spans structure behind one text box, but only when the row is simple
   enough to survive the round trip. */
function linesField(item, sub) {
  if (!isSimpleLines(item.lines)) {
    return el('p', { className: 'hint', textContent: 'This row contains a link or bold text and is changed by your web person.' });
  }
  const input = el('input', { className: 'input', type: 'text', value: linesToText(item.lines) });
  input.oninput = () => { item.lines = textToLines(input.value); changed(); };
  return labelled(sub, input);
}

const ITEM_NOUN = { Events: 'event', Cards: 'card', Photos: 'photo', Officers: 'officer',
                    Buttons: 'button', Points: 'point', Rows: 'row' };

function move(list, index, delta) {
  const target = index + delta;
  if (target < 0 || target >= list.length) return;
  const [item] = list.splice(index, 1);
  list.splice(target, 0, item);
  changed({ drawer: true, now: true });
}

function labelled(spec, control) {
  const row = el('label', { className: 'field' }, [
    el('span', { className: 'field-label', textContent: spec.label + (spec.required ? ' (needed)' : '') }),
    control,
  ]);
  if (spec.hint) row.append(el('span', { className: 'field-hint', textContent: spec.hint }));
  return row;
}

function uploadButton(input, obj, key) {
  const picker = el('input', { type: 'file', accept: 'image/*', className: 'hidden-file' });
  const button = el('button', { className: 'btn btn--quiet', type: 'button', textContent: 'Choose a photo…',
    onclick: () => picker.click() });
  picker.onchange = async () => {
    const file = picker.files && picker.files[0];
    if (!file) return;
    button.textContent = 'Uploading…';
    button.disabled = true;
    try {
      const form = new FormData();
      form.append('file', file);
      form.append('dest', 'site');
      const res = await fetch('../api/upload', { method: 'POST', body: form });
      const body = await res.json();
      if (!res.ok || !body.ok) throw new Error(body.error || 'Upload failed.');
      input.value = body.path;
      obj[key] = body.path;
      changed({ now: true });
    } catch (e) {
      alert('That photo couldn’t be uploaded. ' + (e.message || ''));
    } finally {
      button.textContent = 'Choose a photo…';
      button.disabled = false;
    }
  };
  return el('span', { className: 'upload-wrap' }, [button, picker]);
}

/* ---------- sections and pages ("Add or move sections") ----------
   The page's structure, for the rarer jobs: a new section, a different kind of block,
   reordering, a new page. Everyday changes never need it. */

function layoutPanel(body) {
  const page = curPage();
  body.append(el('div', { className: 'page-meta' }, [
    simpleField('Page address', page.slug, (v) => { page.slug = v; }, 'Lowercase, no spaces. The page lives at ' + page.slug + '.html'),
    simpleField('Name in the browser tab', page.title || '', (v) => { page.title = v; }),
  ]));

  (page.sections || []).forEach((section, si) => {
    const box = el('div', { className: 'section-box' });
    box.append(el('div', { className: 'section-head' }, [
      el('span', { className: 'section-name', textContent: 'Section ' + (si + 1) }),
      chip('Tinted', section.tint, (v) => { section.tint = v; }),
      chip('Dark', section.dark, (v) => { section.dark = v; }),
      el('button', { className: 'mv mv--x', type: 'button', textContent: 'Remove section',
        onclick: () => {
          if (!confirm('Remove section ' + (si + 1) + ' and everything in it?')) return;
          page.sections.splice(si, 1);
          changed({ drawer: true, now: true });
        } }),
    ]));
    box.append(blockList({ section: si, chain: [] }, section.blocks = section.blocks || []));
    body.append(box);
  });
  body.append(el('button', { className: 'btn btn--add', type: 'button', textContent: '+ Add a section',
    onclick: () => { page.sections = page.sections || []; page.sections.push({ blocks: [] }); changed({ drawer: true, now: true }); } }));
  body.append(el('button', { className: 'btn btn--quiet', type: 'button', textContent: '+ Add a new page', onclick: addPage }));
  return 'Sections on this page';
}

function blockList(basePath, blocks) {
  const list = el('div', { className: 'block-list' });
  blocks.forEach((block, bi) => {
    const path = { section: basePath.section, chain: basePath.chain.concat([{ index: bi, key: 'blocks' }]) };
    const label = BLOCK_LABELS[block.type] ? BLOCK_LABELS[block.type][0] : block.type;
    const row = el('div', { className: 'block-row' });
    row.append(el('button', { className: 'block-name', type: 'button', textContent: label + summarise(block),
      onclick: () => openDrawer({ kind: 'block', path: pathKey(path) }) }));
    row.append(el('button', { className: 'mv', type: 'button', textContent: 'Up', disabled: bi === 0, onclick: () => move(blocks, bi, -1) }));
    row.append(el('button', { className: 'mv', type: 'button', textContent: 'Down', disabled: bi === blocks.length - 1, onclick: () => move(blocks, bi, 1) }));
    list.append(row);
    if (block.type === 'group') {
      list.append(el('div', { className: 'nest' }, blockList({ section: basePath.section, chain: path.chain }, block.blocks = block.blocks || [])));
    } else if (block.type === 'split') {
      for (const side of ['left', 'right']) {
        list.append(el('div', { className: 'nest' }, [
          el('div', { className: 'nest-label', textContent: side === 'left' ? 'Left column' : 'Right column' }),
          blockList({ section: basePath.section, chain: path.chain.slice(0, -1).concat([{ index: bi, key: side }]) }, block[side] = block[side] || []),
        ]));
      }
    }
  });
  list.append(addBlockSelect(blocks));
  return list;
}

function addBlockSelect(target) {
  const select = el('select', { className: 'input add-select' });
  select.setAttribute('aria-label', 'Add something to this section');
  select.append(el('option', { value: '', textContent: '+ Add something here…' }));
  for (const [type, [name, hint]] of Object.entries(BLOCK_LABELS)) {
    select.append(el('option', { value: type, textContent: name + ' — ' + hint }));
  }
  select.onchange = () => {
    if (!select.value) return;
    target.push(BLOCK_DEFAULTS[select.value]());
    select.value = '';
    changed({ drawer: true, now: true });
  };
  return select;
}

/* A few words from the block itself, so the list is scannable without opening every row. */
function summarise(block) {
  const first = block.title || block.text || block.heading ||
                (Array.isArray(block.items) && block.items.length
                  ? (typeof block.items[0] === 'string' ? block.items[0] : block.items[0].title || block.items[0].label || block.items[0].name || '')
                  : '');
  const text = String(first || '').replace(/\s+/g, ' ').trim();
  return text ? ' · ' + (text.length > 34 ? text.slice(0, 34) + '…' : text) : '';
}

function simpleField(label, value, onInput, hint) {
  const input = el('input', { className: 'input', type: 'text', value: value || '' });
  input.oninput = () => { onInput(input.value); changed(); };
  return labelled({ label, hint }, input);
}

function chip(label, value, onChange) {
  const input = el('input', { type: 'checkbox', checked: !!value });
  input.onchange = () => { onChange(input.checked); changed({ now: true }); };
  return el('label', { className: 'chip' }, [input, el('span', { textContent: label })]);
}

function addPage() {
  const slug = prompt('Address for the new page (lowercase, no spaces):', 'new-page');
  if (!slug) return;
  const s = slug.trim().toLowerCase();
  state.content.pages.push({ slug: s, navHref: s + '.html', title: 'New page', hero: { variant: 'page', title: 'New page' }, sections: [{ blocks: [] }] });
  state.page = state.content.pages.length - 1;
  fillPageSelect();
  changed({ drawer: true, now: true });
}

/* ---------- save / discard ---------- */

async function saveSite() {
  if (state.saving) return;
  pruneBlankItem();
  state.saving = true;
  updateStatus();
  $('#save').textContent = 'Saving…';
  try {
    const res = await fetch('../api/save', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ content: state.content, site: state.site, base: state.base }),
    });
    const body = await res.json().catch(() => ({}));
    if (res.status === 401) { showSignIn(); return; }
    if (!res.ok || !body.ok) throw new Error(body.error || 'Saving didn’t work. Please try again.');
    if (body.base) state.base = body.base;   // what the site now holds, so the next save passes
    state.pristine = snapshot();
    state.dirty = false;
    state.note = 'Saved. The website shows your changes in about a minute.';
  } catch (e) {
    state.error = e.message;
  } finally {
    state.saving = false;
    $('#save').textContent = 'Save changes';
    updateStatus();
  }
}

function discard() {
  if (!confirm('Throw away the changes you haven’t saved? The page goes back to how it was at the last save.')) return;
  const p = JSON.parse(state.pristine);
  state.content = p.content;
  state.site = p.site;
  state.drawer = null;
  if (state.page >= state.content.pages.length) state.page = 0;
  fillPageSelect();
  renderDrawer();
  changed({ now: true });
}

/* ---------- sign in ---------- */

function showSignIn() { $('#signin').hidden = false; $('#app').hidden = true; }
function showApp() { $('#signin').hidden = true; $('#app').hidden = false; }

async function signIn(event) {
  event.preventDefault();
  const error = $('#signin-error');
  error.textContent = '';
  const res = await fetch('../api/login', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ username: $('#username').value, password: $('#password').value }),
  }).catch(() => null);
  const body = res ? await res.json().catch(() => ({})) : {};
  if (!res || !res.ok || !body.ok) { error.textContent = body.error || 'That didn’t work. Please try again.'; return; }
  await start();
}

/* ---------- event sign-ups (D1, NOT content) ----------
   Who registered. This lives in the database and never touches the website's files (see
   functions/api/rsvp.js). Registration itself is switched on per event, on the page, in the
   event's details — this screen is for reading, exporting and tidying the lists. */

function setMode(m) {
  const content = m === 'content';
  $('#content-view').hidden = !content;
  $('#savebar').hidden = !content;
  $('#events-view').hidden = content;
  if (!content) { state.drawer = null; renderDrawer(); }
  for (const [id, on] of [['#mode-content', content], ['#mode-events', !content]]) {
    $(id).classList.toggle('is-on', on);
    $(id).setAttribute('aria-pressed', on ? 'true' : 'false');
  }
  if (!content) loadEvents();
}

const when = (iso) => {
  const d = new Date(iso);
  return isNaN(d) ? '' : d.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
};

async function loadEvents() {
  const view = $('#events-view');
  view.textContent = '';
  view.append(el('h1', { className: 'ev-h', textContent: 'Event sign-ups' }));
  view.append(el('p', { className: 'hint', textContent: 'People who registered on the website. To let people register for an event, go to “Change the website”, open the Events page, press “Event details” on the event and tick “Let people register on the website”, then save.' }));
  const list = el('div', { className: 'ev-list', textContent: 'Loading…' });
  view.append(list);
  let events = [];
  try {
    const r = await fetch('../api/events').then((x) => x.json());
    if (!r.ok) throw new Error(r.error);
    events = r.events;
  } catch (e) { list.textContent = 'The sign-ups couldn’t be loaded. ' + (e.message || 'Please refresh the page.'); return; }
  list.textContent = '';
  if (!events.length) { list.append(el('p', { className: 'empty', textContent: 'No events are taking registrations yet.' })); return; }
  events.forEach((ev) => list.append(eventCard(ev)));
}

function eventCard(ev) {
  const seats = ev.seats || 0;
  const closed = !!ev.closed;
  const box = el('div', { className: 'ev-rsvps', hidden: true });
  const view = el('button', { className: 'btn btn--primary', type: 'button', textContent: `See who registered (${seats})` });
  view.addEventListener('click', () => {
    box.hidden = !box.hidden;
    view.textContent = box.hidden ? `See who registered (${seats})` : 'Hide the list';
    if (!box.hidden) loadRsvps(ev, box);
  });
  const toggle = el('button', { className: 'btn btn--quiet', type: 'button',
    textContent: closed ? 'Start taking sign-ups again' : 'Stop taking sign-ups' });
  toggle.addEventListener('click', async () => {
    toggle.disabled = true;
    try {
      await fetch('../api/events', { method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: ev.id, title: ev.title, capacity: ev.capacity, closed: closed ? 0 : 1 }) });
    } catch {}
    loadEvents();
  });
  const actions = [view, toggle];
  if (seats === 0) {   // the server refuses to delete an event that still has sign-ups (they'd cascade)
    const del = el('button', { className: 'btn btn--danger', type: 'button', textContent: 'Delete this event’s sign-up list' });
    del.addEventListener('click', async () => {
      if (!confirm(`Delete the sign-up list for “${ev.title}”? It’s empty.`)) return;
      del.disabled = true;
      const res = await fetch('../api/events/delete', { method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: ev.id }) }).then((x) => x.json()).catch(() => ({ ok: false, error: 'Network error.' }));
      if (!res.ok) { del.disabled = false; alert(res.error || 'That couldn’t be deleted.'); return; }
      loadEvents();
    });
    actions.push(del);
  }
  return el('section', { className: 'ev-card' }, [
    el('div', { className: 'ev-card-head' }, [
      el('h2', { className: 'ev-name', textContent: ev.title }),
      el('span', { className: 'ev-badge ' + (closed ? 'ev-badge--closed' : 'ev-badge--open'),
        textContent: closed ? 'Not taking sign-ups' : 'Taking sign-ups' }),
      el('span', { className: 'ev-seats', textContent: `${seats} registered` + (ev.capacity ? ` of ${ev.capacity} places` : '') }),
    ]),
    el('div', { className: 'ev-actions' }, actions),
    box,
  ]);
}

async function loadRsvps(ev, box) {
  box.textContent = 'Loading…';
  let data;
  try { data = await fetch('../api/rsvps?event_id=' + encodeURIComponent(ev.id)).then((x) => x.json()); }
  catch { box.textContent = 'The list couldn’t be loaded. Please try again.'; return; }
  if (!data.ok) { box.textContent = data.error || 'The list couldn’t be loaded.'; return; }
  const rsvps = data.rsvps;
  box.textContent = '';
  const head = el('div', { className: 'ev-rsvps-head' }, [
    el('p', { className: 'ev-count', textContent: `${rsvps.length} ${rsvps.length === 1 ? 'person' : 'people'} registered` }),
  ]);
  if (rsvps.length) {
    head.append(el('a', { className: 'btn btn--quiet', href: '../api/rsvps?format=csv&event_id=' + encodeURIComponent(ev.id),
      textContent: 'Download the list (spreadsheet)' }));
  }
  box.append(head);
  if (!rsvps.length) { box.append(el('p', { className: 'empty', textContent: 'Nobody has registered yet.' })); return; }
  const table = el('table', { className: 'ev-table' });
  table.append(el('thead', {}, el('tr', {}, ['Name', 'Phone', 'Email', 'Registered', ''].map((h) => el('th', { scope: 'col', textContent: h })))));
  const tb = el('tbody');
  for (const r of rsvps) {
    const tel = String(r.phone || '').replace(/[^+\d]/g, '');
    const del = el('button', { className: 'btn btn--danger btn--sm', type: 'button', textContent: 'Remove' });
    del.addEventListener('click', async () => {
      if (!confirm(`Remove ${r.name} from the list?`)) return;
      del.disabled = true;
      const res = await fetch('../api/rsvps/delete', { method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: r.id }) }).then((x) => x.json()).catch(() => ({ ok: false }));
      if (res.ok) loadRsvps(ev, box); else { del.disabled = false; alert(res.error || 'That couldn’t be removed.'); }
    });
    // Every value goes in as text (el sets textContent): names and emails come from strangers.
    tb.append(el('tr', {}, [
      el('td', { textContent: r.name }),
      el('td', {}, r.phone ? el('a', { href: 'tel:' + tel, textContent: r.phone }) : ''),
      el('td', {}, el('a', { href: 'mailto:' + r.email, textContent: r.email })),
      el('td', { textContent: when(r.created_at) }),
      el('td', {}, del),
    ]));
  }
  table.append(tb);
  box.append(el('div', { className: 'ev-table-wrap' }, table));
}

/* ---------- boot ---------- */

function fillPageSelect() {
  const sel = $('#page-select');
  sel.textContent = '';
  state.content.pages.forEach((p, i) => sel.append(el('option', { value: String(i), textContent: pageName(i), selected: i === state.page })));
}

async function start() {
  await loadSite();
  showApp();
  fillPageSelect();
  renderPreview();
  updateStatus();
}

window.addEventListener('beforeunload', (e) => {
  if (state.dirty) { e.preventDefault(); e.returnValue = ''; }
});

$('#signin-form').addEventListener('submit', signIn);
$('#save').addEventListener('click', saveSite);
$('#discard').addEventListener('click', discard);
$('#drawer-close').addEventListener('click', closeDrawer);
$('#open-layout').addEventListener('click', () => openDrawer({ kind: 'layout' }));
$('#page-select').addEventListener('change', (e) => {
  pruneBlankItem();
  state.page = Number(e.target.value);
  state.drawer = null;
  renderDrawer();
  changed({ now: true });
});
// A save that was refused points at the thing to fix: clicking the message opens it.
$('#status').addEventListener('click', () => {
  const m = state.errorPath && /^pages\[(\d+)\]/.exec(state.errorPath);
  if (!m) return;
  const item = /^pages\[\d+\]\.(.*?\.items\[\d+\])/.exec(state.errorPath);
  state.page = Number(m[1]);
  fillPageSelect();
  renderPreview();
  if (item) openDrawer({ kind: 'item', path: item[1].replace(/\[(\d+)\]/g, '.$1') });
});
document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && state.drawer) closeDrawer(); });
$('#mode-content').addEventListener('click', () => setMode('content'));
$('#mode-events').addEventListener('click', () => setMode('events'));

/* The session cookie is HttpOnly, so the page cannot read it. /api/session is the
   honest way to ask — rather than probing some other endpoint and inferring the
   answer from which error it returns. */
fetch('../api/session')
  .then((r) => (r.ok ? start() : showSignIn()))
  .catch(showSignIn);
